### ISSUE TITLE
And if o don't want the flag? 🙄

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/mdn-minimalist#399]
And if o don't want the flag? 🙄
Make It optional

```html
<a
hreflang="fr"
data-flag
>
```

```css
a[hreflang="fr"][data-flag]:before{
 content: url(flags/fr.svg);
}
```

_Originally posted by @mattiapontonio in https://github.com/mdn/content/issues/842#issuecomment-753695370_

Please see all the other issue.
