### ISSUE TITLE
add back arrow utility class

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-minimalist#535]
It would be useful to simply be able to add a class called `back` to an element and have it add an arrow pointing in a backward direction.

For example:

![Screenshot of a link with an arrow pointing backward](https://user-images.githubusercontent.com/10350960/111430804-933f8f80-8703-11eb-8e3c-617e45571358.png)

Code used on the complete sign-in page

```css
.back {
    &::before {
      background: transparent url("~@mdn/dinocons/arrows/arrow.svg") 0 0/14px
        no-repeat;
      content: "";
      display: inline-block;
      height: 14px;
      margin-right: $base-spacing / 4;
      transform: rotate(-90deg);
      vertical-align: middle;
      width: 14px;
    }

    &:hover,
    &:focus {
      &::before {
        margin-right: $base-spacing / 3;
      }
    }
  }
```
